In [1]:
import numpy as np

In [12]:
X = np.array([[1,2], [3,4], [5,6], [7,8], [9,10]])
X

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [14]:
X[[0, 1, 3]]

array([[1, 2],
       [3, 4],
       [7, 8]])

In [25]:
np.random.seed(42)

In [26]:
np.random.randint(0, 10 + 1)

6

In [27]:
np.random.randint(0, 10 + 1)

3

In [32]:
X[[np.random.randint(0, X.shape[0] + 1), np.random.randint(0, X.shape[0] + 1)]]

array([[7, 8],
       [5, 6]])

In [41]:
X_bootstrapped = X[np.random.randint(0, X.shape[0], size=X.shape[0])]

In [44]:
X_bootstrapped.shape == X.shape

True